global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ml-model-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'system-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'model-inference'
    static_configs:
      - targets: ['host.docker.internal:5002']
    scrape_interval: 5s
    metrics_path: '/metrics'